apiVersion: apps/v1
kind: Deployment
metadata:
  name: hutechexamserver-depl
  labels:
    app: hutechexam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hutechexamserver
  template:
    metadata:
      labels:
        app: hutechexamserver
    spec:
      containers:
      - name: hutechexamserver
        image: hiendatcao13/hutechexamserver:latest