apiVersion: v1
kind: Service
metadata:
  name: hutechexamserver-np-srv
  labels:
    app: hutechexamserver
spec:
  type: NodePort
  selector:
    app: hutechexamserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007